import requests
import os
from dotenv import load_dotenv
from st2common.runners.base_action import Action # type: ignore

# Load environment variables from .env
load_dotenv('/opt/stackstorm/packs/kepsoar/.env')

class AlertHistory(Action):
    def run(self, script, log_id, caution):
        datas = {
        "blocks": [
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"Response script generated by the AI Agent: ```\n{script}\n```"
                }
            },
            {
                "type": "divider",
            },
            {
                "type": "context",
                "elements": [
                    {
                    "type": "mrkdwn",
                    "text": "👀 To see which attack this responds to, please check the detection log.",
                    },
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": "*This script will be executed*",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"```\n{script}\n```",
                },
            },
            {
                "type": "actions",
                "elements": [
                    {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Run response script",
                    },
                    "style": "primary",
                    "value": f"{script}",
                    "action_id": "execute_script",
                    },
                    {
                    "type": "button",
                    "text": {
                        "type": "plain_text",
                        "text": "Edit response script",
                    },
                    "style": "danger",
                    "value": f"{script}",
                    "action_id": "edit_script",
                    },
                ],
                },
            ],
            "metadata": {
                "event_type": "agent_value",
                "event_payload": {
                    "log_id": log_id,
                    "caution_level": caution,
                }
            }
        }
        headers = {"Content-type": "application/json"}
        url = os.getenv("SLACK_HISTORY_URL")
        print(datas)
        try:
            response = requests.post(url, headers=headers, json=datas)
            return (True, response)
        except:
            return (False, "Post failed")
